go_import_path: github.com/kaappi/kaappi-operator
sudo: required
dist: xenial
language: go

go:
- 1.11.x

env:
  global:
    - CHANGE_MINIKUBE_NONE_USER=true
    - MINIKUBE_WANTUPDATENOTIFICATION=false
    - MINIKUBE_WANTREPORTERRORPROMPT=false
    - MINIKUBE_HOME=$HOME
    - CHANGE_MINIKUBE_NONE_USER=true
    - KUBECONFIG=$HOME/.kube/config
    - KUBE_VERSION="1.14.1"

before_install:
# Install Dep, GolangCI lint, Operator SDK, kubectl, and Minikube
- ./hack/prerequisites.sh
# Create empty KUBECONFIG & Docker configuration files
- mkdir -p $HOME/.kube $HOME/.minikube $HOME/.docker && touch $KUBECONFIG && echo "{}" > $HOME/.docker/config.json
# Start Minikube
- sudo $GOPATH/bin/minikube start --vm-driver=none --kubernetes-version=v${KUBE_VERSION} --memory=5120
- "sudo chown -R travis: /home/travis/.minikube/"

install:
# Download Go package dependencies
- dep ensure -v -vendor-only

before_script:
# Create a namespace for the operator testing
- kubectl create namespace operator-test

script:
# Run lints
- make lint
# Run unit tests
- make test
# Run e2e tests
- make test-e2e
